apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashy
  namespace: dashy
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - dashy.blascolab.com
      secretName: dashy-tls
  rules:
    - host: dashy.blascolab.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashy-auth
                port:
                  number: 80
