apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dashy
resources:
  - ../../base/dashy/
  - ingress.yaml
  - dashy-tls-secret.yaml
patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: dashy-oauth2-config
  - path: oauth2-proxy-hostalias-patch.yaml
    target:
      kind: Deployment
      name: dashy-oauth2-proxy
