apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: keycloak
data:
  KC_HOSTNAME: "keycloak.localtest.me"
  KC_DB_URL_DATABASE: "keycloak"
  DB_USERNAME: "keycloak"
  KC_PROXY: "edge"
  KC_HTTP_ENABLED: "true"
