apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - namespace.yaml
  - keycloaks.crd.yaml
  - keycloakrealmimports.crd.yaml
  - operator.yaml
  - secrets.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - networkpolicy.yaml
  - keycloak.yaml
  - realm-import.yaml
