apiVersion: v1
kind: Service
metadata:
  name: dashy
  namespace: dashy
  labels:
    app: dashy
spec:
  selector:
    app: dashy
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
