apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - ../../base/keycloak/
patches:
  - path: keycloak-hostname-patch.yaml
    target:
      kind: Keycloak
      name: keycloak
